### ISSUE TITLE
ParseTreeWalker failing from version 2.9.1

### ISSUE THREAD

**Issue by aly76** [nawforce/apex-parser#11]
Hi @nawforce 

The `ParseTreeWalker` seems to be failing from version 2.9.1, where dependencies were updated. I think this could potentially be an issue with the new pre-release of antlr4ts `0.5.0-alpha.4` , but wondering if you have any ideas on the cause and how to fix it. 

`Cannot read property 'enterRule' of undefined`

Thanks

**Comment by nawforce** [comment]
I have not seen this myself. I tried running sfpowerkit:source:apextest:list using 2.9.1 over some sample projects and all looked good, it was reporting test classes. Do you have an example case where this fails that I could take a look at?

**Comment by aly76** [comment]
Thanks for your help @nawforce, found the issue. The dependencies in package-lock files were outdated for sfpowerscripts.

**Comment by nawforce** [comment]
Cool, glad you found it, I should have flagged the dependency change with a major version, I will make sure I do next time.
