### ISSUE TITLE
Failing to parse System.runAs() and testMethod modifier 

### ISSUE THREAD

**Issue by aly76** [nawforce/apex-parser#3]
Failing to parse System.runAs() and testMethod modifier.  
There are no issues with the test classes in the developer console.

**Error 1**
SyntaxException { line: 36, column: 24, message: "missing ';' at '{'" }
```        
System.runAs(u) { 
  ...
}
```

**Error 2**
SyntaxException {
  line: 5,
  column: 19,
  message: "no viable alternative at input 'testMethod void'"
}

```
static testMethod void testParse() {
  ...
}
```

**Comment by nawforce** [comment]
Thanks @aly76 I will take a look at them, think they are likely problems caused from the port to JS, I use the same grammar in Java and would have noticed if either of these failed.

**Comment by nawforce** [comment]
I have not been able to reproduce this against a test set of 15k files. You can get these errors if you don't use the CaseInsensitiveInputStream with ANTLR, see example in README.md.

**Comment by aly76** [comment]
Thanks @nawforce , CaseInsensitiveInputStream fixed the problem.
