### ISSUE TITLE
Publish latest Maven artifact version

### ISSUE THREAD

**Issue by aaronhurst-google** [nawforce/apex-parser#34]
I'd love to get some of your latest changes into the Maven artifact that's being used by the experimental PMD branch. (Some of them will be required for the tests to pass.) Hopefully there is an opportune time to cut a release in the not-too-distant future. Thanks in advance!

**Comment by nawforce** [comment]
Ok, will see if we can get a new version done. I was hoping we would have swapped to new home by now as we talked about earlier in the year but it's taking some time to get the paperwork done.

**Comment by adangel** [comment]
Hi @nawforce ,
I think I found the new home -> https://github.com/apex-dev-tools
Any news about when the repositories will be public? especially https://github.com/apex-dev-tools/apex-parser
The apex-link related repos would also be good... (see https://github.com/pmd/pmd/pull/4465)
Thanks!

**Comment by nawforce** [comment]
That is the new home. I have been cross-merging on apex-parser repo, there is a minor difference in API but largely they are in sync. The apex-link side has changed more substantially but we should be able to swap over once its available. I will comment on https://github.com/pmd/pmd/pull/4465 with some more details.
