### ISSUE TITLE
N_DAYS_AGO and similar missing

### ISSUE THREAD

**Issue by cwarden** [nawforce/apex-parser#40]
`N_DAYS_AGO:N` and similar date formulas are missing from the lexer and parser:

https://github.com/octoberswimmer/apexfmt/commit/1575a2aa464808443a5baf9a3b55c0ceb4260ff3#diff-626bff9b234037dce23312a9a14261edbc492cfb5cbac98de736372d82dc85f4R216-R222

**Comment by adangel** [comment]
Actually, this is already existing:

https://github.com/nawforce/apex-parser/blob/160f3ff19da1d7db240d48476e4db8776749e433/antlr/ApexLexer.g4#L204

Same with:
* N_WEEKS_AGO_N
* N_MONTHS_AGO_N
* N_QUARTERS_AGO_N
* N_FISCAL_QUARTERS_AGO_N
* N_YEARS_AGO_N
* N_FISCAL_YEARS_AGO_N

This ApexParser seems to support all possible formats, that are documented here: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm

**Comment by cwarden** [comment]
Looks like my working copy was outdated, and I pulled the version from  c70ff8cb080df2210788538d92f1be2939a867c4 into [apexfmt](https://github.com/octoberswimmer/apexfmt/commit/a1578aa39e1ceef8a0d2ec42fdb49420e321afac).
